# Generated by Django 5.2.16 on 2026-08-01 19:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('note', 'Note'), ('entity', 'Entity'), ('session', 'Session')], max_length=20)),
                ('title', models.CharField(max_length=240)),
                ('body', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('canon', 'Canon'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archive_items', to='campaigns.campaign')),
            ],
            options={
                'ordering': ['-updated_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Alias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=160)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='campaigns.archiveitem')),
            ],
        ),
        migrations.CreateModel(
            name='ItemRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('snapshot', models.JSONField()),
                ('reason', models.CharField(blank=True, max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='campaigns.archiveitem')),
            ],
            options={
                'ordering': ['-number'],
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(default='active', max_length=20)),
                ('current_version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='campaigns.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='PublicationVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='campaigns.publication')),
            ],
        ),
        migrations.CreateModel(
            name='PublicationEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('safe_title', models.CharField(max_length=240)),
                ('safe_body', models.TextField(blank=True)),
                ('safe_fields', models.JSONField(default=dict)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='campaigns.archiveitem')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='campaigns.publicationversion')),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=160)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_references', to='campaigns.archiveitem')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_references', to='campaigns.archiveitem')),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=80)),
                ('reciprocal_label', models.CharField(blank=True, max_length=80)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relationships', to='campaigns.archiveitem')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relationships', to='campaigns.archiveitem')),
            ],
        ),
        migrations.CreateModel(
            name='SessionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_for', models.DateField(blank=True, null=True)),
                ('session_status', models.CharField(default='planned', max_length=20)),
                ('outcome_text', models.TextField(blank=True)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='session_detail', to='campaigns.archiveitem')),
            ],
        ),
        migrations.CreateModel(
            name='SessionLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_sessions', to='campaigns.archiveitem')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_links', to='campaigns.archiveitem')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='campaigns.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='ItemTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_tags', to='campaigns.archiveitem')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='campaigns.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('applies_to', models.CharField(default='entity', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='campaigns.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='TemplateVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('fields', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='campaigns.template')),
            ],
            options={
                'ordering': ['template', '-number'],
            },
        ),
        migrations.CreateModel(
            name='EntityDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_type', models.CharField(default='person', max_length=20)),
                ('field_values', models.JSONField(default=dict)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='entity_detail', to='campaigns.archiveitem')),
                ('template_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='campaigns.templateversion')),
            ],
        ),
        migrations.AddIndex(
            model_name='archiveitem',
            index=models.Index(fields=['campaign', 'kind', 'status'], name='campaigns_a_campaig_68410d_idx'),
        ),
        migrations.AddIndex(
            model_name='archiveitem',
            index=models.Index(fields=['campaign', 'updated_at'], name='campaigns_a_campaig_c20ea5_idx'),
        ),
        migrations.AddConstraint(
            model_name='alias',
            constraint=models.UniqueConstraint(fields=('item', 'value'), name='unique_item_alias'),
        ),
        migrations.AddConstraint(
            model_name='itemrevision',
            constraint=models.UniqueConstraint(fields=('item', 'number'), name='unique_item_revision'),
        ),
        migrations.AddConstraint(
            model_name='publicationversion',
            constraint=models.UniqueConstraint(fields=('publication', 'number'), name='unique_publication_version'),
        ),
        migrations.AddConstraint(
            model_name='publicationentry',
            constraint=models.UniqueConstraint(fields=('version', 'item'), name='unique_publication_entry'),
        ),
        migrations.AddConstraint(
            model_name='reference',
            constraint=models.UniqueConstraint(fields=('source', 'target', 'label'), name='unique_item_reference'),
        ),
        migrations.AddConstraint(
            model_name='relationship',
            constraint=models.UniqueConstraint(fields=('source', 'target', 'kind'), name='unique_item_relationship'),
        ),
        migrations.AddConstraint(
            model_name='sessionlink',
            constraint=models.UniqueConstraint(fields=('session', 'item'), name='unique_session_item_link'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('campaign', 'name'), name='unique_campaign_tag'),
        ),
        migrations.AddConstraint(
            model_name='itemtag',
            constraint=models.UniqueConstraint(fields=('item', 'tag'), name='unique_item_tag'),
        ),
        migrations.AddConstraint(
            model_name='template',
            constraint=models.UniqueConstraint(fields=('campaign', 'name'), name='unique_campaign_template_name'),
        ),
        migrations.AddConstraint(
            model_name='templateversion',
            constraint=models.UniqueConstraint(fields=('template', 'number'), name='unique_template_version'),
        ),
    ]
